language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-user-api ./udagram-api
  - docker build -t udagram-feed-api ./udagram-feed-api
  - docker tag udagram-frontend mfathy89/udagram-frontend:latest
  - docker tag udagram-user-api mfathy89/udagram-user-api:latest
  - docker tag udagram-feed-api mfathy89/udagram-feed-api:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mfathy89/udagram-user-api
  - docker push mfathy89/udagram-feed-api
  - docker push mfathy89/udagram-frontend