apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    service: backend-feed
spec:
  ports:
  - name: "destination-port"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: backend-feed