apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   service: frontend-app
 name: frontend-app
spec:
 replicas: 1
 selector:
  matchLabels:
    service: frontend-app
 template:
   metadata:
     labels:
       service: frontend-app
   spec:
     containers:
     - image: mfathy89/udagram-frontend
       name: udagram-frontend
       imagePullPolicy: Always 
       ports:
       - containerPort: 80
       resources:
         requests:
           memory: "64Mi"
           cpu: "250m"
         limits:
           memory: "1024Mi"
           cpu: "500m"      
     restartPolicy: Always